name: Build and Test

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Start services
      run: |
        docker-compose up -d

    - name: Stop services
      run: |
        docker-compose down
